"""Rename word_id to word_seq.

Revision ID: 1090f36628d2
Revises: bcb05cc72fd3
Create Date: 2021-06-20 23:57:04.247405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1090f36628d2'
down_revision = 'bcb05cc72fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran_word_text', sa.Column('word_seq', sa.Integer(), nullable=False))
    op.drop_column('quran_word_text', 'word_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran_word_text', sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('quran_word_text', 'word_seq')
    # ### end Alembic commands ###
