"""correction

Revision ID: 3a68acad78c1
Revises: e4d108156f8f
Create Date: 2021-06-23 01:02:16.618696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a68acad78c1'
down_revision = 'e4d108156f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quran_word_text', 'is_correct')
    op.drop_column('quran_word_text', 'hafiz_id')
    op.add_column('recording_word', sa.Column('hafiz_id', sa.Integer(), nullable=True))
    op.add_column('recording_word', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording_word', 'is_correct')
    op.drop_column('recording_word', 'hafiz_id')
    op.add_column('quran_word_text', sa.Column('hafiz_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quran_word_text', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
