"""correct the name

Revision ID: 56d045746e3c
Revises: 1090f36628d2
Create Date: 2021-06-21 00:05:52.461862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d045746e3c'
down_revision = '1090f36628d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran_word_text', sa.Column('surah_number', sa.Integer(), nullable=False))
    op.drop_column('quran_word_text', 'suarh_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran_word_text', sa.Column('suarh_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('quran_word_text', 'surah_number')
    # ### end Alembic commands ###
