"""Change data type from largebinary to json.

Revision ID: 6f706df0e865
Revises: 59cdf77a86d3
Create Date: 2021-06-29 00:53:12.787549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f706df0e865'
down_revision = '59cdf77a86d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran_ayah_text', sa.Column('ayah', sa.JSON(), nullable=False))
    op.drop_column('quran_ayah_text', 'ayah_arabic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran_ayah_text', sa.Column('ayah_arabic', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('quran_ayah_text', 'ayah')
    # ### end Alembic commands ###
