"""Make relation with quran_words_text to variations.

Revision ID: bfbe9cf93272
Revises: e41013382200
Create Date: 2021-08-03 00:16:50.642226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbe9cf93272'
down_revision = 'e41013382200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quran_word_text', 'word_arabic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quran_word_text', 'word_arabic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
