"""create_many_to_many_relation.

Revision ID: e41013382200
Revises: e41013383300
Create Date: 2021-07-31 16:23:32.199947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41013382200'
down_revision = 'e41013383300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variations', 'word_ids')
    op.create_table('variation_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variation_id'], ['variations.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['quran_word_text.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variations', sa.Column('word_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_table('variation_words')
    # ### end Alembic commands ###