"""add word_ids array into variation table. Store words separately.

Revision ID: e41013383300
Revises: 01e3ed07968e
Create Date: 2021-07-31 16:23:32.199947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41013383300'
down_revision = '01e3ed07968e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quran_word_text_ayah_text_id_fkey', 'quran_word_text', type_='foreignkey')
    op.drop_constraint('quran_word_text_ayah_variation_id_fkey', 'quran_word_text', type_='foreignkey')
    op.drop_column('quran_word_text', 'ayah_text_id')
    op.drop_column('quran_word_text', 'word_seq')
    op.drop_column('quran_word_text', 'ayah_variation_id')
    op.add_column('variations', sa.Column('word_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variations', 'word_ids')
    op.add_column('quran_word_text', sa.Column('ayah_variation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quran_word_text', sa.Column('word_seq', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quran_word_text', sa.Column('ayah_text_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('quran_word_text_ayah_variation_id_fkey', 'quran_word_text', 'variations', ['ayah_variation_id'], ['id'])
    op.create_foreign_key('quran_word_text_ayah_text_id_fkey', 'quran_word_text', 'quran_ayah_text', ['ayah_text_id'], ['id'])
    # ### end Alembic commands ###
