"""Remove some fields from reciter_info, Add some fields into recording_sentence and recording_word tables.

Revision ID: e4d108156f8f
Revises: 56d045746e3c
Create Date: 2021-06-23 00:55:35.160491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4d108156f8f'
down_revision = '56d045746e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran_word_text', sa.Column('hafiz_id', sa.Integer(), nullable=True))
    op.add_column('quran_word_text', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.drop_column('reciter_info', 'audio_clarity')
    op.drop_column('reciter_info', 'with_tajweed')
    op.drop_column('reciter_info', 'audio_format')
    op.drop_column('reciter_info', 'mistakes')
    op.drop_column('reciter_info', 'background_noise_level')
    op.drop_column('reciter_info', 'audio_length_seconds')
    op.drop_column('reciter_info', 'number_of_mistakes')
    op.add_column('recording_sentence', sa.Column('hafiz_id', sa.Integer(), nullable=True))
    op.add_column('recording_sentence', sa.Column('audio_clarity', sa.String(), nullable=True))
    op.add_column('recording_sentence', sa.Column('background_noise_level', sa.String(), nullable=True))
    op.add_column('recording_sentence', sa.Column('with_tajweed', sa.Boolean(), nullable=True))
    op.add_column('recording_sentence', sa.Column('number_of_mistakes', sa.Integer(), nullable=True))
    op.add_column('recording_sentence', sa.Column('mistakes', sa.JSON(), nullable=True))
    op.add_column('recording_sentence', sa.Column('audio_format', sa.String(), nullable=True))
    op.add_column('recording_sentence', sa.Column('audio_length_seconds', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording_sentence', 'audio_length_seconds')
    op.drop_column('recording_sentence', 'audio_format')
    op.drop_column('recording_sentence', 'mistakes')
    op.drop_column('recording_sentence', 'number_of_mistakes')
    op.drop_column('recording_sentence', 'with_tajweed')
    op.drop_column('recording_sentence', 'background_noise_level')
    op.drop_column('recording_sentence', 'audio_clarity')
    op.drop_column('recording_sentence', 'hafiz_id')
    op.add_column('reciter_info', sa.Column('number_of_mistakes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reciter_info', sa.Column('audio_length_seconds', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('reciter_info', sa.Column('background_noise_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reciter_info', sa.Column('mistakes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reciter_info', sa.Column('audio_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reciter_info', sa.Column('with_tajweed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reciter_info', sa.Column('audio_clarity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('quran_word_text', 'is_correct')
    op.drop_column('quran_word_text', 'hafiz_id')
    # ### end Alembic commands ###
