"""change in variation table.

Revision ID: f63127834429
Revises: a4cae3208adf
Create Date: 2021-07-13 20:30:50.170262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f63127834429'
down_revision = 'a4cae3208adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variations', sa.Column('variation_number', sa.Integer(), nullable=False))
    op.add_column('variations', sa.Column('sentence_ids', sa.String(), nullable=False))
    op.drop_column('variations', 'is_variation')
    op.drop_column('variations', 'ayaah_variations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variations', sa.Column('ayaah_variations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variations', sa.Column('is_variation', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('variations', 'sentence_ids')
    op.drop_column('variations', 'variation_number')
    # ### end Alembic commands ###
